language: python
python:
  - "3.7.0"

install:
  - pip install -r requirements.txt
  - pip install pytest pytest-cov

# command to run tests
script:
  - pytest --cov=app/

after_success:
  - coveralls